# Generated by Django 4.1.7 on 2023-03-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faunaweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='place english name')),
                ('place_national', models.CharField(max_length=200, verbose_name='place national name')),
            ],
            options={
                'verbose_name': 'place',
                'verbose_name_plural': 'places',
                'ordering': ['place_national'],
            },
        ),
    ]
