# Generated by Django 4.1.7 on 2023-03-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faunaweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalclass',
            name='example_image',
            field=models.ImageField(blank=True, null=True, upload_to='faunaweb/classes/', verbose_name='example image'),
        ),
    ]
