# Generated by Django 4.1.7 on 2023-03-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faunaweb', '0002_animalclass_example_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mammalsclass',
            old_name='animal_class',
            new_name='class_id',
        ),
        migrations.AddField(
            model_name='mammalsclass',
            name='family_national',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='order national name'),
        ),
    ]
