# Generated by Django 4.1.7 on 2023-03-15 18:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faunaweb', '0002_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='date')),
                ('count', models.IntegerField(default=1, verbose_name='count')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_profile/observations', verbose_name='photo')),
                ('observer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observation', to=settings.AUTH_USER_MODEL, verbose_name='observer')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observation', to='faunaweb.place', verbose_name='place')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observation', to='faunaweb.animalspecies', verbose_name='animal species')),
            ],
            options={
                'verbose_name': 'observation',
                'verbose_name_plural': 'observations',
                'ordering': ['-date'],
            },
        ),
    ]
