# Generated by Django 4.1.7 on 2023-03-20 07:29

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('faunaweb', '0003_observation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(blank=True, max_length=4000, null=True, verbose_name='content')),
            ],
        ),
    ]
