# Generated by Django 4.1.7 on 2023-03-13 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faunaweb', '0003_rename_animal_class_mammalsclass_class_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mammalsclass',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mammals', to='faunaweb.animalclass', verbose_name='animal class'),
        ),
        migrations.CreateModel(
            name='ReptilesClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_scientific', models.CharField(max_length=200, verbose_name='order scientific name')),
                ('order_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='order national name')),
                ('family_scientific', models.CharField(max_length=200, verbose_name='family scientific name')),
                ('family_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='order national name')),
                ('species_scientific', models.CharField(max_length=200, verbose_name='species scientific name')),
                ('species_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='species english name')),
                ('species_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='species national name')),
                ('endangered', models.BooleanField(default=False, verbose_name='endangered species')),
                ('species_image', models.ImageField(blank=True, null=True, upload_to='faunaweb/species/', verbose_name='species image')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reptiles', to='faunaweb.animalclass', verbose_name='animal class')),
            ],
            options={
                'verbose_name': 'reptiles class species',
                'verbose_name_plural': 'reptiles class species',
                'ordering': ['order_scientific', 'species_scientific'],
            },
        ),
        migrations.CreateModel(
            name='RayfinnedFishesClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_scientific', models.CharField(max_length=200, verbose_name='order scientific name')),
                ('order_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='order national name')),
                ('family_scientific', models.CharField(max_length=200, verbose_name='family scientific name')),
                ('family_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='order national name')),
                ('species_scientific', models.CharField(max_length=200, verbose_name='species scientific name')),
                ('species_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='species english name')),
                ('species_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='species national name')),
                ('endangered', models.BooleanField(default=False, verbose_name='endangered species')),
                ('species_image', models.ImageField(blank=True, null=True, upload_to='faunaweb/species/', verbose_name='species image')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rayfinned_fishes', to='faunaweb.animalclass', verbose_name='animal class')),
            ],
            options={
                'verbose_name': 'ray-finned fishes class species',
                'verbose_name_plural': 'ray-finned fishes class species',
                'ordering': ['order_scientific', 'species_scientific'],
            },
        ),
        migrations.CreateModel(
            name='MalacostracansClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_scientific', models.CharField(max_length=200, verbose_name='order scientific name')),
                ('order_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='order national name')),
                ('family_scientific', models.CharField(max_length=200, verbose_name='family scientific name')),
                ('family_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='order national name')),
                ('species_scientific', models.CharField(max_length=200, verbose_name='species scientific name')),
                ('species_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='species english name')),
                ('species_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='species national name')),
                ('endangered', models.BooleanField(default=False, verbose_name='endangered species')),
                ('species_image', models.ImageField(blank=True, null=True, upload_to='faunaweb/species/', verbose_name='species image')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='malacostracans', to='faunaweb.animalclass', verbose_name='animal class')),
            ],
            options={
                'verbose_name': 'malacostracans class species',
                'verbose_name_plural': 'malacostracans class species',
                'ordering': ['order_scientific', 'species_scientific'],
            },
        ),
        migrations.CreateModel(
            name='InsectsClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_scientific', models.CharField(max_length=200, verbose_name='order scientific name')),
                ('order_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='order national name')),
                ('family_scientific', models.CharField(max_length=200, verbose_name='family scientific name')),
                ('family_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='order national name')),
                ('species_scientific', models.CharField(max_length=200, verbose_name='species scientific name')),
                ('species_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='species english name')),
                ('species_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='species national name')),
                ('endangered', models.BooleanField(default=False, verbose_name='endangered species')),
                ('species_image', models.ImageField(blank=True, null=True, upload_to='faunaweb/species/', verbose_name='species image')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insects', to='faunaweb.animalclass', verbose_name='animal class')),
            ],
            options={
                'verbose_name': 'insects class species',
                'verbose_name_plural': 'insects class species',
                'ordering': ['order_scientific', 'species_scientific'],
            },
        ),
        migrations.CreateModel(
            name='BirdsClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_scientific', models.CharField(max_length=200, verbose_name='order scientific name')),
                ('order_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='order national name')),
                ('family_scientific', models.CharField(max_length=200, verbose_name='family scientific name')),
                ('family_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='order national name')),
                ('species_scientific', models.CharField(max_length=200, verbose_name='species scientific name')),
                ('species_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='species english name')),
                ('species_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='species national name')),
                ('endangered', models.BooleanField(default=False, verbose_name='endangered species')),
                ('species_image', models.ImageField(blank=True, null=True, upload_to='faunaweb/species/', verbose_name='species image')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='birds', to='faunaweb.animalclass', verbose_name='animal class')),
            ],
            options={
                'verbose_name': 'birds class species',
                'verbose_name_plural': 'birds class species',
                'ordering': ['order_scientific', 'species_scientific'],
            },
        ),
        migrations.CreateModel(
            name='ArachnidsClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_scientific', models.CharField(max_length=200, verbose_name='order scientific name')),
                ('order_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='order national name')),
                ('family_scientific', models.CharField(max_length=200, verbose_name='family scientific name')),
                ('family_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='order national name')),
                ('species_scientific', models.CharField(max_length=200, verbose_name='species scientific name')),
                ('species_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='species english name')),
                ('species_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='species national name')),
                ('endangered', models.BooleanField(default=False, verbose_name='endangered species')),
                ('species_image', models.ImageField(blank=True, null=True, upload_to='faunaweb/species/', verbose_name='species image')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arachnids', to='faunaweb.animalclass', verbose_name='animal class')),
            ],
            options={
                'verbose_name': 'arachnids class species',
                'verbose_name_plural': 'arachnids class species',
                'ordering': ['order_scientific', 'species_scientific'],
            },
        ),
        migrations.CreateModel(
            name='AmphibiansClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_scientific', models.CharField(max_length=200, verbose_name='order scientific name')),
                ('order_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='order national name')),
                ('family_scientific', models.CharField(max_length=200, verbose_name='family scientific name')),
                ('family_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='order national name')),
                ('species_scientific', models.CharField(max_length=200, verbose_name='species scientific name')),
                ('species_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='species english name')),
                ('species_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='species national name')),
                ('endangered', models.BooleanField(default=False, verbose_name='endangered species')),
                ('species_image', models.ImageField(blank=True, null=True, upload_to='faunaweb/species/', verbose_name='species image')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amphibians', to='faunaweb.animalclass', verbose_name='animal class')),
            ],
            options={
                'verbose_name': 'amphibians class species',
                'verbose_name_plural': 'amphibians class species',
                'ordering': ['order_scientific', 'species_scientific'],
            },
        ),
    ]
