# Generated by Django 4.1.7 on 2023-03-13 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faunaweb', '0005_alter_rayfinnedfishesclass_class_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amphibians',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_scientific', models.CharField(max_length=200, verbose_name='order scientific name')),
                ('order_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='order national name')),
                ('family_scientific', models.CharField(max_length=200, verbose_name='family scientific name')),
                ('family_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='order national name')),
                ('species_scientific', models.CharField(max_length=200, verbose_name='species scientific name')),
                ('species_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='species english name')),
                ('species_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='species national name')),
                ('endangered', models.BooleanField(default=False, verbose_name='endangered species')),
                ('species_image', models.ImageField(blank=True, null=True, upload_to='faunaweb/species/', verbose_name='species image')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='faunaweb.animalclass', verbose_name='animal class')),
            ],
            options={
                'verbose_name': 'amphibians species',
                'verbose_name_plural': 'amphibians species',
            },
        ),
        migrations.CreateModel(
            name='Arachnids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_scientific', models.CharField(max_length=200, verbose_name='order scientific name')),
                ('order_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='order national name')),
                ('family_scientific', models.CharField(max_length=200, verbose_name='family scientific name')),
                ('family_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='order national name')),
                ('species_scientific', models.CharField(max_length=200, verbose_name='species scientific name')),
                ('species_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='species english name')),
                ('species_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='species national name')),
                ('endangered', models.BooleanField(default=False, verbose_name='endangered species')),
                ('species_image', models.ImageField(blank=True, null=True, upload_to='faunaweb/species/', verbose_name='species image')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='faunaweb.animalclass', verbose_name='animal class')),
            ],
            options={
                'verbose_name': 'arachnids species',
                'verbose_name_plural': 'arachnids species',
            },
        ),
        migrations.CreateModel(
            name='Birds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_scientific', models.CharField(max_length=200, verbose_name='order scientific name')),
                ('order_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='order national name')),
                ('family_scientific', models.CharField(max_length=200, verbose_name='family scientific name')),
                ('family_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='order national name')),
                ('species_scientific', models.CharField(max_length=200, verbose_name='species scientific name')),
                ('species_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='species english name')),
                ('species_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='species national name')),
                ('endangered', models.BooleanField(default=False, verbose_name='endangered species')),
                ('species_image', models.ImageField(blank=True, null=True, upload_to='faunaweb/species/', verbose_name='species image')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='faunaweb.animalclass', verbose_name='animal class')),
            ],
            options={
                'verbose_name': 'birds species',
                'verbose_name_plural': 'birds species',
            },
        ),
        migrations.CreateModel(
            name='Insects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_scientific', models.CharField(max_length=200, verbose_name='order scientific name')),
                ('order_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='order national name')),
                ('family_scientific', models.CharField(max_length=200, verbose_name='family scientific name')),
                ('family_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='order national name')),
                ('species_scientific', models.CharField(max_length=200, verbose_name='species scientific name')),
                ('species_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='species english name')),
                ('species_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='species national name')),
                ('endangered', models.BooleanField(default=False, verbose_name='endangered species')),
                ('species_image', models.ImageField(blank=True, null=True, upload_to='faunaweb/species/', verbose_name='species image')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='faunaweb.animalclass', verbose_name='animal class')),
            ],
            options={
                'verbose_name': 'insects species',
                'verbose_name_plural': 'insects species',
            },
        ),
        migrations.CreateModel(
            name='Malacostracans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_scientific', models.CharField(max_length=200, verbose_name='order scientific name')),
                ('order_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='order national name')),
                ('family_scientific', models.CharField(max_length=200, verbose_name='family scientific name')),
                ('family_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='order national name')),
                ('species_scientific', models.CharField(max_length=200, verbose_name='species scientific name')),
                ('species_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='species english name')),
                ('species_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='species national name')),
                ('endangered', models.BooleanField(default=False, verbose_name='endangered species')),
                ('species_image', models.ImageField(blank=True, null=True, upload_to='faunaweb/species/', verbose_name='species image')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='faunaweb.animalclass', verbose_name='animal class')),
            ],
            options={
                'verbose_name': 'malacostracans species',
                'verbose_name_plural': 'malacostracans species',
            },
        ),
        migrations.CreateModel(
            name='Mammals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_scientific', models.CharField(max_length=200, verbose_name='order scientific name')),
                ('order_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='order national name')),
                ('family_scientific', models.CharField(max_length=200, verbose_name='family scientific name')),
                ('family_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='order national name')),
                ('species_scientific', models.CharField(max_length=200, verbose_name='species scientific name')),
                ('species_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='species english name')),
                ('species_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='species national name')),
                ('endangered', models.BooleanField(default=False, verbose_name='endangered species')),
                ('species_image', models.ImageField(blank=True, null=True, upload_to='faunaweb/species/', verbose_name='species image')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='faunaweb.animalclass', verbose_name='animal class')),
            ],
            options={
                'verbose_name': 'mammals species',
                'verbose_name_plural': 'mammals species',
            },
        ),
        migrations.CreateModel(
            name='RayfinnedFishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_scientific', models.CharField(max_length=200, verbose_name='order scientific name')),
                ('order_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='order national name')),
                ('family_scientific', models.CharField(max_length=200, verbose_name='family scientific name')),
                ('family_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='order national name')),
                ('species_scientific', models.CharField(max_length=200, verbose_name='species scientific name')),
                ('species_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='species english name')),
                ('species_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='species national name')),
                ('endangered', models.BooleanField(default=False, verbose_name='endangered species')),
                ('species_image', models.ImageField(blank=True, null=True, upload_to='faunaweb/species/', verbose_name='species image')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='faunaweb.animalclass', verbose_name='animal class')),
            ],
            options={
                'verbose_name': 'ray-finned fishes species',
                'verbose_name_plural': 'ray-finned fishes species',
            },
        ),
        migrations.CreateModel(
            name='Reptiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_scientific', models.CharField(max_length=200, verbose_name='order scientific name')),
                ('order_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='order national name')),
                ('family_scientific', models.CharField(max_length=200, verbose_name='family scientific name')),
                ('family_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='order national name')),
                ('species_scientific', models.CharField(max_length=200, verbose_name='species scientific name')),
                ('species_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='species english name')),
                ('species_national', models.CharField(blank=True, max_length=200, null=True, verbose_name='species national name')),
                ('endangered', models.BooleanField(default=False, verbose_name='endangered species')),
                ('species_image', models.ImageField(blank=True, null=True, upload_to='faunaweb/species/', verbose_name='species image')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='faunaweb.animalclass', verbose_name='animal class')),
            ],
            options={
                'verbose_name': 'reptiles species',
                'verbose_name_plural': 'reptiles species',
            },
        ),
        migrations.RemoveField(
            model_name='arachnidsclass',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='birdsclass',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='insectsclass',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='malacostracansclass',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='mammalsclass',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='rayfinnedfishesclass',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='reptilesclass',
            name='class_id',
        ),
        migrations.DeleteModel(
            name='AmphibiansClass',
        ),
        migrations.DeleteModel(
            name='ArachnidsClass',
        ),
        migrations.DeleteModel(
            name='BirdsClass',
        ),
        migrations.DeleteModel(
            name='InsectsClass',
        ),
        migrations.DeleteModel(
            name='MalacostracansClass',
        ),
        migrations.DeleteModel(
            name='MammalsClass',
        ),
        migrations.DeleteModel(
            name='RayfinnedFishesClass',
        ),
        migrations.DeleteModel(
            name='ReptilesClass',
        ),
    ]
